version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jakarta.annotation:jakarta.annotation-api
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.el:jakarta.el-api
    versions:
    - ">= 4.0.0"
  - dependency-name: org.glassfish:jakarta.el
    versions:
    - ">= 4.0.0"
  - dependency-name: net.trajano.wagon:wagon-git
    versions:
    - ">= 2.0.4"
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - "> 9.1.0"
  - dependency-name: org.apache.tomcat:tomcat-servlet-api
    versions:
    - "> 9.1.0"
  - dependency-name: org.apache.tomcat:tomcat-jasper-el
    versions:
    - "> 9.1.0"
  - dependency-name: org.apache.tomcat:tomcat-jasper
    versions:
    - "> 9.1.0"
  - dependency-name: org.apache.tomcat:tomcat-coyote
    versions:
    - "> 9.1.0"
